version: "3.9"

services:

  # ===================
  # MongoDB
  # ===================
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # ===================
  # RabbitMQ
  # ===================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  # ===================
  # Eureka Server
  # ===================
  eureka-server:
    image: flight-eureka-server
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  # ===================
  # Config Server
  # ===================
  config-server:
    image: flight-config-server
    container_name: config-server
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker

  # ===================
  # Auth Service
  # ===================
  auth-service:
    image: flight-auth-service
    container_name: auth-service
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
      - eureka-server
      - config-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/authdb
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888

  # ===================
  # API Gateway
  # ===================
  api-gateway:
    image: flight-api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - eureka-server
      - config-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888

  # ===================
  # Flight Service
  # ===================
  flight-service:
    image: flight-flight-service
    container_name: flight-service
    restart: always
    ports:
      - "8091:8091"
    depends_on:
      - mongodb
      - eureka-server
      - config-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/flightmicrodb
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888

  # ===================
  # Booking Service
  # ===================
  booking-service:
    image: flight-booking-service
    container_name: booking-service
    restart: always
    ports:
      - "8092:8092"
    depends_on:
      - mongodb
      - rabbitmq
      - flight-service
      - eureka-server
      - config-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/bookingmicrodb
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888

  # ===================
  # Notification Service
  # ===================
  notification-service:
    image: flight-notification-service
    container_name: notification-service
    restart: always
    ports:
      - "8093:8093"
    depends_on:
      - rabbitmq
      - eureka-server
      - config-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888

volumes:
  mongo_data:
